In [10]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [47]:
data=pd.read_csv('/content/diabetes.csv')

In [48]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [49]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [50]:
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [51]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [52]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=32)

In [53]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [54]:
X_train.size

4912

In [55]:
X_test.size

1232

In [56]:
X_train

array([[-0.84574616, -0.46116412, -0.61466591, ..., -1.01555797,
        -0.8448966 , -1.03789011],
       [ 0.92455433,  2.39012328,  1.07939438, ...,  0.99201638,
        -0.05528399,  0.65201847],
       [-1.14079624, -0.83715807, -0.50878714, ..., -0.4456659 ,
         0.18698352, -0.95339468],
       ...,
       [ 0.62950425, -1.24448484, -0.19115084, ..., -0.76946821,
        -0.46803603,  0.65201847],
       [ 0.92455433,  0.13415962,  0.0206067 , ..., -0.86013286,
        -0.92266148,  0.31403676],
       [-1.14079624,  0.66681771,  0.76175808, ...,  0.03356153,
        -0.10912121, -0.95339468]])

In [57]:
clf = RandomForestClassifier(random_state=0)

In [58]:
clf.fit(X_train,y_train)

RandomForestClassifier(random_state=0)

In [59]:
y_pred=clf.predict(X_test)

In [60]:
acc=accuracy_score(y_test,y_pred)

In [61]:
print(acc)

0.7922077922077922

In [62]:
cm=confusion_matrix(y_test,y_pred)

In [63]:
print(cm)

[[86 13]
 [19 36]]

In [64]:
X_test

array([[ 0.62950425,  0.85481468,  0.55000054, ..., -0.34204916,
        -0.87181521,  1.41247734],
       [ 0.92455433,  0.69815053,  1.07939438, ..., -0.22548032,
        -1.02136305,  0.82100933],
       [-0.55069608, -0.02250452, -3.6851502 , ..., -1.62430632,
         1.08427057,  3.27137678],
       ...,
       [-0.84574616, -0.93115655, -0.40290838, ..., -0.91194123,
         2.38832776, -0.69990839],
       [ 1.21960441,  1.48147125,  1.92642453, ...,  0.70707035,
        -0.91069765,  0.82100933],
       [ 1.21960441,  0.19682528,  0.23236424, ..., -0.80832449,
        -0.91967052,  0.48302762]])

In [65]:
class_rep=classification_report(y_test,y_pred)

In [66]:
print(class_rep)

              precision    recall  f1-score   support

           0       0.82      0.87      0.84        99
           1       0.73      0.65      0.69        55

    accuracy                           0.79       154
   macro avg       0.78      0.76      0.77       154
weighted avg       0.79      0.79      0.79       154